version: '3.8'

services:
  db:
    networks:
      - app_network
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    networks:
      - app_network
    build: .
    volumes:
      - .:/app
      - ./static:/app/static  # Bind mount for static files
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 zombie_train_backend.wsgi:application"

  nginx:
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/app/static  # Bind mount for static files
      - ./certs:/etc/letsencrypt  # Bind mount for Let's Encrypt certificates
    depends_on:
      - web
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
