services:
  officer:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    networks:
      - app_network
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    networks:
      - app_network
    build: .
    volumes:
      - .:/app
      - ./static:/app/static  # Bind mount for static files
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 zombie_train_backend.wsgi:application"
    labels:
      deck-chores.execute-new-day.command: sh -c "python /app/manage.py new_day"
      deck-chores.execute-new-day.interval: "daily"

  nginx:
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/app/static  # Bind mount for static files
      - ./certs:/etc/letsencrypt  # Bind mount for Let's Encrypt certificates
    depends_on:
      - backend
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
